# This is a workflow to run integration-tests for raft

name: bft-integration-tests

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bft-integration-tests:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up a golang dev env
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # Installs ginkgo and gomega
      - name: Install Pre-reqs
        run: go install -mod=mod github.com/onsi/ginkgo/ginkgo@v1.16.4 && go get github.com/onsi/gomega/...

      - name: Vendor
        run: go mod tidy -go=1.16 && go mod tidy -go=1.17 && go mod vendor

      - name: Pre-Requisites
        run: |
          make docker
          docker pull couchdb:3.2.2
      - name: Integration Tests
        run: ginkgo -v ./integration/raft/...
